#!/usr/bin/python3

from sys import argv

def factorize(number):
       a = 2

    if number < 2:
        return
    print()
    print(number, "<- number-before")
    while number % a:
        a += 1
    print("{:.0f}={:.0f}*{:.0f}".format(number, number / i, i))
    print(number, "<- number-after")
    print()

if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number = int(line.split('\n')[0])
            factorize(number)
            line = file.readline()
except:
    pass
