#!/usr/bin/python3

from sys import argv

def factorize(number):
    a =2

    if number < 2:
        return
    while number > 1:
        if number % a == 0:
            print("{:.0f}={:.0f}*{:.0f}".format(number, number / a, a))
            break
        a += 1

if len(argv) != 2:
    exit()
try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            number = int(line.split('\n')[0])
            factorize(number)
            line = file.readline()
except:
    pass
